"""The summary tables: per-family p-value bookkeeping, sparse marking, settings lookup."""

import json

import pytest

from noncanon import summary


def write_cell(tmp_path, name, arm, flags, correct, tokens=2000, temperature=1.0):
    d = tmp_path / name
    (d / "metrics").mkdir(parents=True)
    with (d / "metrics" / "analysis.jsonl").open("w") as f:
        for i, (flagged, ok) in enumerate(zip(flags, correct)):
            f.write(json.dumps({"file": f"{arm}.parquet", "finish_reason": "stop", "correct": ok, "n_tokens": tokens, "n_units": tokens,
                                "nc_events": int(flagged), "event_positions": [100] if flagged else []}) + "\n")
    (d / f"{arm}.meta.json").write_text(json.dumps({"sampling": {"temperature": temperature, "top_p": 1.0}}))
    return d


def test_ladder_p_values_are_per_family_and_sparse_tests_are_marked(tmp_path, capsys):
    a = write_cell(tmp_path, "a", "untruncated", [1] * 5 + [0] * 45, [True] * 50)
    b = write_cell(tmp_path, "b", "untruncated", [1] * 25 + [0] * 25, [True] * 50)
    c = write_cell(tmp_path, "c", "untruncated", [1] * 3 + [0] * 47, [True] * 3 + [False] * 47)  # 3 correct rollouts: sparse
    summary.ladder([f"X:s1={a}", f"Y:s1={c}", f"X:s2={b}"], "untruncated")
    rows = [line for line in capsys.readouterr().out.splitlines() if line.startswith("| ")][1:]  # drop the header
    x1, y1, x2 = rows
    assert "| — | — |" in x1 and "| — | — |" in y1  # first stage of each family
    assert "| 2e-05 |" in x2 and y1.count("—") >= 2  # X:s2 is tested against X:s1 (5/50 vs 25/50), never against Y
    assert f"(3/3){summary.SPARSE}" in y1


def test_pairs_reads_settings_and_fails_clearly_without_meta(tmp_path, capsys):
    a = write_cell(tmp_path, "a", "untruncated", [1, 0, 0, 0], [True] * 4, temperature=1.0)
    b = write_cell(tmp_path, "b", "recommended", [0, 0, 0, 0], [True] * 4, temperature=0.6)
    summary.pairs([f"m={a}:untruncated,{b}:recommended"], ("u", "r"), None)
    out = capsys.readouterr().out
    assert "T=1.0, top-p=1.0 / T=0.6, top-p=1.0" in out and summary.SPARSE in out
    (b / "recommended.meta.json").unlink()
    with pytest.raises(FileNotFoundError, match="recommended.meta.json"):
        summary.pairs([f"m={a}:untruncated,{b}:recommended"], ("u", "r"), None)


def test_p_str_thresholds():
    assert summary.fmt_p(1e-12) == "1e-12" and summary.fmt_p(0.00042) == "4e-04" and summary.fmt_p(0.0479) == "0.048"
    assert float(summary.omnibus([(5, 50), (25, 50), (3, 50)])) < 1e-6
    assert summary.omnibus([(0, 50), (0, 50)]) == "—"


def test_check_results_diffs_and_rewrites_generated_blocks(tmp_path):
    import subprocess, sys
    md = tmp_path / "R.md"
    block = "<details><summary>Generated by</summary>\n\n```\necho one; \\\n    echo two\n```\n\n</details>\n\n"
    md.write_text("intro\n" + block + "stale\n<!-- end generated -->\ntail\n")
    script = str(__import__("pathlib").Path(__file__).resolve().parents[2] / "scripts" / "check_results.py")
    r = subprocess.run([sys.executable, script, "--file", str(md)], capture_output=True, text=True)
    assert r.returncode == 1 and "MISMATCH" in r.stdout and "-stale" in r.stdout and "+two" in r.stdout
    r = subprocess.run([sys.executable, script, "--file", str(md), "--write"], capture_output=True, text=True)
    assert r.returncode == 0 and md.read_text() == "intro\n" + block + "one\ntwo\n<!-- end generated -->\ntail\n"
    r = subprocess.run([sys.executable, script, "--file", str(md)], capture_output=True, text=True)
    assert r.returncode == 0 and "all 1 generated blocks match" in r.stdout
    # A command that prints nothing must not blank the block; an unterminated block must be refused.
    md.write_text("intro\n" + block.replace("echo one; \\\n    echo two", "true") + "keep\n<!-- end generated -->\n")
    r = subprocess.run([sys.executable, script, "--file", str(md), "--write"], capture_output=True, text=True)
    assert r.returncode == 1 and "FAILED" in r.stdout and "keep" in md.read_text()
    md.write_text("intro\n" + block + "body\n" + block + "body2\n<!-- end generated -->\n")
    r = subprocess.run([sys.executable, script, "--file", str(md)], capture_output=True, text=True)
    assert r.returncode == 1 and "openers" in r.stderr


def test_pairwise_table_annotates_direction_changes(tmp_path, capsys):
    from noncanon import compare

    # a: few flags overall, all early; b: many flags, all late → overall b higher, within 256 a higher.
    a = write_cell(tmp_path, "a", "untruncated", [1] * 10 + [0] * 90, [True] * 100)
    b = write_cell(tmp_path, "b", "untruncated", [1] * 60 + [0] * 40, [True] * 100)
    for d, pos in ((a, 50), (b, 900)):
        lines = (d / "metrics" / "analysis.jsonl").read_text().replace("[100]", f"[{pos}]")
        (d / "metrics" / "analysis.jsonl").write_text(lines)
    compare.print_pairs([f"A vs B={a},{b}", f"correct only: A vs B={a},{b};correct"], "untruncated", seed=0)
    rows = [l for l in capsys.readouterr().out.splitlines() if " vs B |" in l]
    assert rows[0].startswith("| A vs B | 10.0% | 60.0% | ") and "(A higher)" in rows[0] and "(B higher)" not in rows[0]
    assert rows[1].startswith("| correct only: A vs B | 10.0% | 60.0% |")
    assert compare.fmt_p(1.07e-54) == "1e-54" and compare.fmt_p(0.0045) == "0.0045" and compare.fmt_p(0.0253) == "0.025" and compare.fmt_p(0.31) == "0.31"


def test_top_spans_table_counts_spans_and_rollouts(tmp_path, capsys):
    from noncanon import compare

    d = write_cell(tmp_path, "z", "untruncated", [1, 1, 0], [True] * 3)
    with (d / "metrics" / "examples.jsonl").open("w") as f:
        for pid, pieces in (("p", ["a", "b"]), ("p", ["a", "b"]), ("q", ["a", "b"]), ("q", ["c"])):
            f.write(json.dumps({"file": "untruncated.parquet", "prompt_id": pid, "sample": 0, "pos": 1, "emitted": pieces, "canonical": ["".join(pieces)] if pieces != ["c"] else None}) + "\n")
    compare.print_top_spans([f"Z={d}"], "untruncated", 3, "all")
    row = capsys.readouterr().out.splitlines()[-1]
    assert row.startswith("| Z | 3 | 2 | ") and "`a`+`b` → `ab` (3, 2)" in row  # the fragment (canonical None) is not a span
    assert compare.pieces_md(["a|b", "\n"]) == "`a\\|b`+`⏎`"  # pipes escaped for GFM table cells
